repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.8

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile=black]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear==23.3.23]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-pyyaml, types-python-dateutil]
        args: [--ignore-missing-imports, --disallow-untyped-defs, --disallow-incomplete-defs]
        exclude: ^tests/

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore
    -   id: python-no-eval
    -   id: python-use-type-annotations

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.275
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
    -   id: nbqa-black
        additional_dependencies: [black==23.3.0]
    -   id: nbqa-isort
        additional_dependencies: [isort==5.12.0]
    -   id: nbqa-flake8
        additional_dependencies: [flake8==6.0.0, flake8-bugbear==23.3.23]

ci:
  skip: [nbqa-flake8]  # Skip flake8 in CI as it's already run separately
