name: c60
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - scikit-learn=1.5.2
  - pandas=2.2.3
  - numpy=1.26.4
  - networkx=3.3
  - optuna=4.0.0
  - mlflow=2.17.0
  - jupyterlab=4.2.5
  - pytest=8.3.3
  - black=24.8.0
  - fastapi=0.115.2
  - uvicorn=0.32.0
  - pip
  - pip:
      - pyarrow==17.0.0